# Generated by Django 4.1 on 2022-11-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
