# Generated by Django 4.1 on 2022-11-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_music_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='style',
            field=models.CharField(choices=[('TR', 'trance'), ('TN', 'techno'), ('HS', 'house'), ('EL', 'electro'), ('AM', 'ambient'), ('DB', 'dnb'), ('ND', 'nudisco')], default='HS', max_length=2),
        ),
    ]
