# Generated by Django 4.1 on 2022-11-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_music_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substyle', models.CharField(max_length=20)),
                ('representative', models.TextField(blank=True)),
            ],
        ),
    ]
