# Generated by Django 4.1 on 2022-11-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_submusic'),
    ]

    operations = [
        migrations.AddField(
            model_name='submusic',
            name='style',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
