# Generated by Django 4.1 on 2022-11-05 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_submusic_substyle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submusic',
            old_name='substyle',
            new_name='sub_style',
        ),
    ]
